### ISSUE TITLE
doc - plan de gestión de la calidad

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#10]
## descripcion
definir la gestión de la calidad del producto

## to-do
- [x] elementos sujetos a la revisión de la calidad
- [x] métricas de calidad
- [x] estándares de calidad
- [x] procesos de medición de la calidad
- [x] procesos de analisis de la calidad

## recursos
- PMBOK, plan de gestión de la calidad

**Comment by JSnow11** [comment]
## progreso
el resultado de la priemera versión completa puede encontrarse [aquí](https://github.com/P2JN/doit/wiki/Plan-de-Gesti%C3%B3n-de-la-Calidad)
