### ISSUE TITLE
OS1 Story: asistente 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#126]
## descripción

_como_: usuario

_quiero_: recibir notificaciones y mensajes de ayuda del asitente de la app 

_para_: que el uso de la app me resulte más intuitivo y amigable

## to-do

- [ ] API
    - [ ] modulo nuevo
    - [ ] endpoint de mensajes para cada vista disponible (se pasará url de la vista sustituyendo "/" por "-"
 - [ ] UI
    - [ ] barra lateral derecha  
    - [ ] añadir mensajes / notificaciones de asistente
    - [ ] petición en función de la url

## aceptación

- un usuario recibe mensajes y notificaciones para cada vista
