### ISSUE TITLE
external: Setup inicial MongoDB y Django

### ISSUE THREAD

**Issue by pedalopon** [P2JN/doit#13]
## description 
Initial Django configuration, mongo database configuration and project dependencies as needed.

## to-do
- [x] Configure an initial Django template
- [x] Configure the mongo database
- [x] Add and configure dependencies as needed
- [x] Make an installation manual of the initial application
- [x] Dockerize the app

## accept
- [x] The Django project and database are running fine
- [x] The installation process is documented
