### ISSUE TITLE
config - flujo de autenticación

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#130]
## descripción

El proceso de login / registro presenta fragilidad al uso, en ocasiones los usuarios se quedan en un punto intermedio de autenticación sin poder acceder a la funcionalidad de la app.

Se plantea pasar los interceptores de autenticación a un componente AuthProvider en el que se añadan dichos interceptores y se gestione el token mediante el estado de la app.

## to-do

- [x] Implementar el AuthProvider
- [x] mover el actual AuthProvider que vive en App.tsx
- [x] mover los interceptores de autenticación a dicho provider
- [x] reemplazar el uso de localStorage con el state Storage
