### ISSUE TITLE
config - gestión de errores

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#131]
## descripción

Reemplazar y/o ocultar los errores en ingles por errores en español.

## to-do

- [ ] Componente ErrorHandlerProvider
- [ ] Mover los interceptores de errores al ErrorHandlerProvider
- [ ] Mantener los mensajes de error en contenido
- [ ] Extender el componente ParsedError para que depure más tipos de errores
