### ISSUE TITLE
doc - sprint 3

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#140]
## descripcion
descripción detallada de lo que debe ser documentado, como y donde.

## to-do
- [x] documentar el progreso en el S3
- [x] actualizar control calidad
- [x] actualizar control costes
- [x] actualizar control de interés

## recursos
- wiki
- scrum documents
