### ISSUE TITLE
doc - plan de gestión de los interesados

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#15]
## descripcion
Orientado a la definición del plan de usuario piloto

## to-do
- [x] definición de procesos, (encuestas, analisis ...)
- [x] listado de usuarios iniciales
- [x] planes de extensión de usuarios piloto
