### ISSUE TITLE
doc - plan de gestión de costes

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#17]
## descripcion
elaborar un plan de gestión de costes 

## to-do
- [x] categorias involucradas (equipo, recursos humanos, servidores ...)
- [x] metodo y localización del presupuesto inicial
- [x] proceso de revisión del avance y la desviación

## recursos
- inicio en la wiki

**Comment by JSnow11** [comment]
## progreso
elaboración del [plan de gestión de costes](https://github.com/P2JN/doit/wiki/Plan-de-Gesti%C3%B3n-de-los-Costes)
