### ISSUE TITLE
Acta de Constitución

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#2]
## doc
[click here](https://github.com/P2JN/doit/blob/main/docs/01-inicio/acta-constitucion.md)

## to-do
- [x] Mejorar la descripción de apartados anteriores
- [x] Requisitos
- [x] Definir entregables
- [x] Definir los hitos del proyecto
- [ ] Criterios de salida/Abandono
- [ ] Niveles de autoridad
- [x] Estructura de organización
- [x] Firmas
- [ ] Glosario de Términos

## accept
- Los elementos del acta de constitución aparecen también en la memoria
