### ISSUE TITLE
OP1 Story: lista de objetivos

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#25]
## descripción

_como_: usuario

_quiero_: visualizar una lista (pagina principal) que contiene: mis objetivos, los objetivos ajenos en los que participo y el progreso que llevo en ellos (diario, mensual, ...)

_para_: poder tener una vista general de los objetivos que tengo

## to-do

- [x] Pagina de "mis objetivos"
    - [x] Teaser de objetivo
    - [x] Lista de objetivos
    - [x] Progreso
- [x] API 
    - [x] get objetivos
    - [x] get progreso, (daily (hoy), weekly(esta semana), monthly(este mes) and yearly(este año)) by goal by user

## acceptación
- un usuario puede visualizar todos los objetivos en los que participa de forma sencilla en un listado
- un usuario puede ver su progreso general en dichos objetivos
