### ISSUE TITLE
OP1 Story: detalles de objetivo

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#27]
## descripción

_como_: usuario

_quiero_: poder visualizar los detalles de los objetivos en los que participo, incluyendo información general (y progreso), leaderboard, feed de posts y rendimiento en forma de tabs

_para_: poder tener una visión detallada de toda la información concreta de un objetivo

## to-do

- [x] Página
    - [x] tab de información general, con el progreso
    - [x] tabs vacías para el leaderboard, feed, mis trackings y métricas
- [x] Links
    - [x] link desde cualquier teaser de objetivo 
- [x] API
    - [x] get goal 
    - [x] get objective
    - [x] get progress ( ya implementado en #25 )

## aceptación

- un usuario puede visualizar los detalles de un objetivo fácilmente

**Comment by JSnow11** [comment]
## progreso
- implementada la pagina base de detalles de objetivo
- implementadas funcionalidades de edición y eliminación de goal y objetivos
- implementada la estructura de tabs de la pagina

## preocupaciones
- la eliminación de goals deja en un estado comprometido la aplicación y los gets no funcionan
