### ISSUE TITLE
OP1 Story: crear tracking

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#28]
## descripción

_como_: usuario

_quiero_: poder trackear progreso en un objetivo determinado

_para_: poder indicar el progreso que realizo

## to-do

- [x] Modal de tracking
    - [x] cantidad
    - [ ] progreso + cantidad indicada
    - [x] botón de confirmación
    - [ ] switch para postear el tracking
- [x] Openers
    - [x] teaser de objetivo
    - [ ] detalles de objetivo  
- [x] API
    - [x] create tracking
    - [x] relation (tracking - goal)
    - [ ] create post by tracking
    
## aceptación

- un usuario puede crear un tracking para los objetivos en los que participa de forma sencilla

**Comment by JSnow11** [comment]
## progreso

implementado el modal básico de tracking, el resto de subtareas se incluirán cuando las partes correspondientes sean implementadas
