### ISSUE TITLE
OP2 Story: leaderboard 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#29]
## descripción

_como_: usuario

_quiero_: que en la vista de detalle de objetivo (#27) haya una tab en la que se muestre el progreso de forma social (leaderboard) para objetivos de tipo challenge o coperativos

_para_: fomentar la competividad y la colaboración en los objetivos

## to-do

- [x] tab de leaderboard
    - [x] tabla con el leaderboard paginado, o solo los 5 o 10 mejores y luego tu posición
    - [x] filtrado (por sub-objetivo objective) (diario, semanal ...) 
- [x] API 
    - [x] get leaderboard by goal, ( usa el get progress by user and goal y lo aplica a los participantes del goal y devuelve los resultados ordenados )
    - [x] get progress by user and goal ( reusar el implementado en #25 ) 

## aceptación

- un usuario puede visualizar el leaderboard de un objetivo
- un usuario puede filtrar el leaderboard según los tipos de frecuencia de los subobjetivos
- por defecto se muestra el leaderboard semanal

**Comment by JSnow11** [comment]
## requerimientos backend

necesitamos un endpoint custom que:
- reciba un **goalId** y una frecuencia de objetivo "daily, weekly..."
- devuelva una lista ordenada de los usuarios q participan en la meta con el añadido de **la cantidad** de progreso que llevan respecto a la frecuencia dada

@pedalopon
