### ISSUE TITLE
OP2 Story: comentarios

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#30]
## descripción

_como_: usuario

_quiero_: poder comentar sobre los posts, manteniendo los comentarios ordenados por fecha

_para_: poder interactuar con los posts de mis amigos

## to-do

- [x] lista de comentarios
    - [ ] post details
    - [x] post teaser (reducido, primeros 3) 
- [x] formulario de comentario
    - [x] input de comentario
    - [x] submit
- [x] API
    - [x] create message
    - [x] relation (message-post)   
    - [x] get comments by post

## aceptación

- un usuario puede ver los comentarios de los posts en la vista de detalle y parcialmente en los teasers
- un usuario puede comentar sobre un post
