### ISSUE TITLE
OP2 Story: feed

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#31]
## descripción

_como_: usuario

_quiero_: visualizar un feed de posts de los usuarios a los que sigo

_para_: poder ver las novedades sobre los usuario a los que sigo

## to-do

- [x] página
    - [x] lista de posts
    - [x] teaser de post: (autor, objetivo, mensajes y datos propios)
    - [x] objetivo linkeado al post (si existe)
    - [ ] paginación
- [x] API
    - [x] get followed users posts 
    - [x] get post
    - [x] get goal
- [x] Link
    - [x] desde el menu principal 
    
## aceptación

- un usuario puede visualizar los posts de los usuarios a los que sigue en forma de lista de teasers
- los post teasers tienen el objetivo al que pertenecen linkeado
- la lista es paginada
