### ISSUE TITLE
OP2 Story: likes

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#33]
## descripción

_como_: usuario

_quiero_: poder dar like a un post

_para_: indicar que un post me gusta

## to-do

- [x] post teaser
    - [x] n* de likes  
    - [x] botón de like
    - [x] pre-marcar el botón si ya "me gusta"
- [ ] detalles de post
    - [ ] n* de likes  
    - [ ] botón de like
    - [ ] pre-marcar el botón si ya "me gusta"

## aceptación

- un usuario puede dar like al post de otro usuario
- un usuario puede ver los likes que tiene un post
- un usuario puede quitar su like a un post

**Comment by JSnow11** [comment]
## validación
- solo un like entre usuario y entidad likeada
