### ISSUE TITLE
OP2 Story: notificaciones

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#34]
## descripción

_como_: usuario

_quiero_: recibir notificaciones cuando otros usuario o yo realizamos interacciones sobre entidades que me resulten relevantes o de interes (relacionadas a mi usuario)

_para_: poder estar informado de las últimas interacciones, novedades e información relevante

## to-do

- [x] pagina de notificaciones
- [x] notificación "en vivo" (alert)
    - [x] interacciones del propio usuario
    - [x] get notifications tras navegar a otra pagina 
- [x] API
    - [x] get my notifications
    - [x] crear notificaciones en caliente (interceptors?)

## aceptación

- un usuario recibe notificaciones relevantes sobre su propia actividad
- un usuario recibe notificaciones relevantes sobre la actividad de otros usuarios
- un usuario recibe notificaciones sobre novedades de la app o del asistente de la app
