### ISSUE TITLE
OP2 Story: registro

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#35]
## descripción

_como_: usuario

_quiero_: poder registrarme, hacer login/logout en la aplicación con datos concretos o con mi cuenta de google

_para_: poder crear una cuenta en la app

## to-do

- [ ] integración con google
    - [ ] completar automáticamente los campos requeridos de las cuentas de usuarios internas
    - [ ] oauth 2, pre-guardar el token para gCalendar 
- [x] página / formulario
    - [x] inputs básicos de la cuenta de usuario
    - [x] inputs mínimos para el log in
- [x] botón de logout

## aceptación

- un usuario puede registrarse, logearse y deslogearse
- un usuario puede usar su cuenta de google para crear su cuenta / logear

**Comment by JSnow11** [comment]
## progreso
- registro con login queda fuera de alcance
- se implementa un registro / login / logout base para la app
