### ISSUE TITLE
config - frontend boilerplate

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#38]
## descripción

Necesitamos implementar e incorporar la primera versión de la SPA en react con toda la configuración pertinente

## to-do

- [x] crear la app
- [x] seleccionar e instalar dependencias
- [x] services
- [x] routes
- [x] landing page
- [x] paginas iniciales vacías
- [x] header
- [x] footer
- [x] main menu
- [x] error handling
- [x] notification handling
- [ ] auth
- [x] dev env (CORS)
- [x] servir la app con django

**Comment by JSnow11** [comment]
## Progreso
- se ha implementado un boilerplate inicial para la aplicación react
- se ha implementado una landing page sencilla
- se ha implementado enrutado y una navbar
- se ha implementado un sistema de notificaciones y gestor de errores
- se ha integrado la app con django, es servida por django y también puede comunicarse con la api
