### ISSUE TITLE
OP2 Story: mi perfil / detalles de usuario

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#41]
## descripción

_como_: usuario

_quiero_: poder visualizar datos detallados sobre mi usuario o cualquier otro en una página que unifique (con tabs) mi información personal, mis estadísticas generales, mis posts (feed), mi calendario ...

_para_: poder ver mi actividad o la de otro usuario de forma resumida

## to-do

- [x] página
    - [x] tab de información y edición de datos
    - [x] feed de mis posts (reusar y filtrar #31)
    - [x] tab vacía para settings
- [x] API
    - [x] get my posts
    - [x] get user
    - [x] update user

## aceptación

- un usuario puede dejar de participar en un objetivo

**Comment by JSnow11** [comment]
## validación
- un usuario solo puede editarse / eliminarse a si mismo
