### ISSUE TITLE
config - API keys y documentación

### ISSUE THREAD

**Issue by pedalopon** [P2JN/doit#42]
## descripción
Obetener las api keys de:
- Google para el login
- Google calendar
-  Github 
- Twitter
Documentar información útil de las apis que pueda servir para la implementación.

## to-do

- [x] Google login api keys
- [x] Google calendar apikey
- [ ] Documentación útil de las mismas
- [x] Github Api key
- [x] Twitter Api key

**Comment by pedalopon** [comment]
# Librerías 
- [Google Auth](https://github.com/googleapis/google-api-python-client)
- [Google calendar](https://googleapis.github.io/google-api-python-client/docs/dyn/calendar_v3.html)
- [Twitter](https://github.com/tweepy/tweepy)
# Documentación api
- [Autentificarse servidor backend google](https://developers.google.com/identity/sign-in/web/backend-auth)
- [Api google calendar](https://developers.google.com/calendar/api/v3/reference?hl=en_US)
- [Api twitter](https://developer.twitter.com/en/docs/api-reference-index)
- [Api github](https://docs.github.com/es/rest)
