### ISSUE TITLE
OP3 Story: crear tareas en calendar

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#43]
## descripción

_como_: usuario

_quiero_: que la app me permita sincronizar mis objetivos con mi google calendar, mis objetivos apareceran como tareas (google tasks) diarias, semanales, mensuales o anuales planificadas en mi calendario

_para_: poder visualizar mis objetivos en mi calendario y acceder a los mismos de forma sencilla

## to-do

- [ ] tab o apartado de settings en mi perfil
    - [ ] switch
- [ ] integración backend
    - [ ] al activar se crean tareas para los objetivos activos
    - [ ] al participar o crear un goal con objectives estos se añaden como tareas
    - [ ] al añadir trackings, si se ha completado una tarea esta se marca como completada
    - [ ] al dejar de participar en goals las tareas relacionadas se eliminan
    - [ ] las tareas deben contener links al objetivo y al modal de trackeo del objetivo

## aceptación

- un usuario puede sincronizar y planificar sus objetivos mediante tareas de google task que aparecen en google calendar
