### ISSUE TITLE
OS1 Story: Notificaciones del asistente 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#45]
## descripción

_como_: usuario

_quiero_: que mi asistente genere notificaciones relevantes sobre mi progreso o actividad de forma automática

_para_: tener feedback, información actualizada y fomentar mi interés por mi progreso

## to-do

- [ ] generar notificaciones automáticas
    - [x] en login: bienvenida, ultima vez que logeo e info sobre algunos de los objetivos
    - [x] en tracking: si lleva varios trackings (alomejor 3 o mas) notificar sobre cuantos lleva y realzar la racha, también comparar con otros días, decir si le falta poco, ...
    - [ ] al crear un objetivo: felicitar y preguntar si quiere crear un post para publicarlo a sus amigos
    - [x] al entrar en detalles de un objetivo: información relevante sobre el progreso (como va el día / semana / mes) (si alguien te adelantó en el leaderboard) (si el objetivo esta casi completo) (si queda poco para que termine) y link a la tab de estadísticas

## aceptación

- un usuario recibe notificaciones del asistente de forma constante con info relevante

**Comment by JSnow11** [comment]
unificado en #126
