### ISSUE TITLE
OS2 Story: estadísticas de rendimiento en objetivo 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#46]
## descripción

_como_: usuario

_quiero_: ver datos estadísticos detallados sobre mi progreso y actividad en un goal concreto, incluyendo desviaciones, comparaciones con otros días, semanas, meses, gráfica semanal, ... 

_para_: ver datos relevantes y analizados sobre mi progreso

## to-do

- [x] nuevo modulo stats
- [x] tab de metricas
    - [x] gráfica semanal
    - [x] info de tracking diario, semanal, anual
    - [ ] desviaciones y varianzas del día, semana, mes actual y la media o el anterior
    - [ ] extras
- [x] API
    - [ ] get progreso by goal for día / semana / mes / año concret@

## aceptación

- un usuario puede visualizar datos estadísticos concretos sobre su progreso en un objetivo en la tab de estadísticas

**Comment by JSnow11** [comment]
## cocepto
- Grafica semanal
- Progresos diarios
- Si es cooperativo se devuelve progreso grupal
- Se pasa el lunes de la semana como parametro
- Se devuelve la suma de los trackings de cada día de esa semana
