### ISSUE TITLE
OS2 Story: estadísticas de usuario 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#47]
## descripción

_como_: usuario 

_quiero_: ver estadísticas relevantes sobre mi perfil en relación a objetivos completados, trackings totales, % de completitud de objetivos, participaciones en objetivos ajenos, posts, likes, ...

_para_: tener información relevante sobre mi actividad general en la app

## to-do

- [x] nuevo modulo stats
- [x] tab de estadísticas en mi perfil
    - [ ] goals en los que participa actualmente (query)
    - [ ] goals creados (contador)
    - [ ] goals en los que ha participado en total (contador)
    - [ ] objetivos completados totales, diarios, semanales, mensuales ... (contador)
    - [ ] nº trackings totales (query)
    - [ ] posts totales (query)
    - [ ] likes totales (query)
    - [ ] comments totales (query)
- [x] API
    - [x] get user stats ^ 
    

## aceptación

- un usuario puede obtener información relevante sobre sus estadísticas generales en la app en la pagina de su perfil
