### ISSUE TITLE
OS2 Story: Logros 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#48]
## descripción

_como_: usuario

_quiero_: que la app ofrezca logros completados en la tab de estadísticas de mi perfil

_para_: destacar logros numéricos interesantes en mi perfil y motivarme a conseguirlos

## to-do

- [ ] definir logros posibles
- [ ] definir iconos / svgs para los logros
- [ ] API
    - [ ] get completed achivements by user

## aceptación

- un usuario puede visualizar logros interesantes que ha conseguido por su uso en la app en la pagina de perfil de usuario

**Comment by JSnow11** [comment]
## requisitos
- nueva tabla achievement
    - relación con user
    - relación con media (prepopulado)
    - titulo
    - descripción
- pre-populado inicial
- comprobación de complititud
