### ISSUE TITLE
OA1 Story: integrar tracking con github 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#49]
## descripción

_como_: usuario

_quiero_: poder automatizar el trackeo de mi progreso en aplicaciones como github, creando un objetivo automatizado que tome información de trackeo automáticamente

_para_: agilizar el proceso de tracking y no tener que hacerlo manualmente

## to-do

- [ ] backend
    - [ ] Acceso a la API de github
    - [ ] campo enum "integration" que contenga inicialmente "github - x" como opción y pueda ser null, x indicará el tipo de tracking, por ejemplo, commits
    - [ ] el campo "integration" es null por defecto
    - [ ] si el campo "integration" es "github" obtener información de tracking automaticamente desde la API cada vez que se solicite el objetivo en cuestión antes de hacer get a la base de datos
- [ ] frontend
    - [ ] selector de integración al inicio del form de crear objetivo
    - [ ] desabilitar campos innecesarios 

## aceptación

- un usuario puede crear un objetivo automatizado que tome métricas desde github
