### ISSUE TITLE
OP1 Story: tab de trackings 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#50]
## descripción

_como_: usuario

_quiero_: poder visualizar, editar y eliminar mis trackings en un objetivo en una tab de la vista en detalle de dicho objetivo

_para_: poder corregir errores

## to-do

- [x] tab de trackings
     - [x] añadirla a #27 
     - [x] reusar el modal de #28 
     - [x] teaser de tracking con funcionalidades de edición y eliminación
- [x] API
   - [x] get tracking by user and goal
   - [x] crud tracking

## aceptación

- un usuario puede corregir errores de trackeo consultando, eliminando o editando dichos trackings desde una tab en la vista de detalle del objetivo

**Comment by JSnow11** [comment]
## adicional
- se debe facilitar funcionalidad de eliminación de trackings
- se debe implementar un teaser de tracking
