### ISSUE TITLE
General Story: explore 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#51]
## descripción

_como_: usuario

_quiero_: que se me ofrezca una pagina donde encontrar objetivos, usuarios, posts relevantes, ...

_para_: poder encontrar contenido interesante en el que participar o con el que interactuar

## to-do

- [x] Pagina de Explore
    - [ ] Slideshows para teasers de goal, usuario y post, por diferentes tipos de recomendación
- [ ] API
    - [ ] recomendar usuarios por
        - [ ] followers (cantidad y crecimiento)
        - [ ] actividad (posts y trackings medios)
        - [ ] afinidad (semejanza al usuario o participación en goals semejantes)
        - [ ] puntuación (calculo en #47)  
    - [ ] recomendar goals por:
        - [ ] participantes (cantidad y crecimiento)
        - [ ] following (goals de las personas a las que sigues)
        - [ ] afinidad (goals semejantes a los que participas)
        - [ ] actividad (trackings) (cantidad y crecimiento) 
     - [ ] posts
        - [ ] relevancia (comentarios)
        - [ ] following (goals de las personas a las que sigues)
          

## aceptación

- el usuario puede acceder a una pagina de exploración de contenido relevante, que fomenta su actividad

**Comment by JSnow11** [comment]
Se espera que esta historia se comience a maquetar en el S1 y se implmente funcionalmente (recomendación) en el S2

**Comment by JSnow11** [comment]
## Progreso
- se han implementado los carouseles
- se han implementado los teasers para cada tipo de contenido
- se han implementado visualmente los contadores de distintas métricas para cada teaser
- se ha implementado una base para la pagina de explore

**Comment by JSnow11** [comment]
## necesidades backend
- contadores para distintas entidades
    - seguir ejemplo de "likes" o "numFollowers"
    - Post: numComments
    - User: numPosts
    - Goal: numParticipants, numPosts

@pedalopon

**Comment by JSnow11** [comment]
## review
- esta tarea se da por completa como iniciación a la pgina explore
- se continuará en una tarea de follow up
