### ISSUE TITLE
Story: mis settings

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#53]
## descripción

_como_: usuario

_quiero_: una tab de configuración para mi perfil donde poder configurar integraciones y comportamientos de la app

_para_: poder indicar mis preferencias 

## to-do

- [ ] tab de configuración en #41 
    - [ ] sincronizar con google
    - [ ] switch the sincronización con calendar
    - [ ] switch de creación de posts para un tracking de forma automática
    - [ ] switch de "asistente"
- [ ] API
    - [ ] integración con google y gcalendar
    - [ ] almacenamiento de preferencias
    - [ ] comprobar preferencias y automatización de comportamientos 
        - [ ] crear post cuando se crea un tracking 

## aceptación

-  un usuario puede indicar sus preferencias de configuración en su perfil

**Comment by JSnow11** [comment]
depende de:

#77 
#54 
#49 
#43
