### ISSUE TITLE
OA1 Story: integrar con Strava 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#54]
## descripción

_como_: usuario

_quiero_: poder crear un objetivo que se conecte con Strava y trackee de forma automática mis actividades de running

_para_: tener un objetivo de trackeo automático basado en mi actividad deportiva en strava

## to-do

- [ ] backend
    - [ ] Acceso a la API de strava
    - [ ] campo enum "integration" que contenga inicialmente "strava - x" como opción y pueda ser null, x indicará el tipo de tracking, por ejemplo, commits
    - [ ] el campo "integration" es null por defecto
    - [ ] si el campo "integration" es "strava" obtener información de tracking automaticamente desde la API cada vez que se solicite el objetivo en cuestión antes de hacer get a la base de datos
- [ ] frontend
    - [ ] selector de integración al inicio del form de crear objetivo
    - [ ] desabilitar campos innecesarios 
    - [ ] Switch de integración en #53 

## aceptación

- un usuario puede crear un objetivo automatizado que tome métricas de strava
