### ISSUE TITLE
OP3 Story: Planning de objetivo

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#58]
## descripción

_como_: usuario

_quiero_: que las tareas que se creen en google calendar, aparezcan en una tab de los detalles de cualquier objetivo que tenga planificación generada

_para_: tener una vision interna de mi planificación y el cumplimiento de la misma en la app

> esta story tiene alta relación con #19 y #23 , podría unificarse con #46 

## to-do

- [ ] tab detalles de objetivo
    - [ ] tabla semanal
    - [ ] mostrar tareas (cantidad) objetivo por semana
    - [ ] mostrar ultima semana o semana en curso
    - [ ] mostrar media
- [ ]  API
    - [ ] get tareas por semana
    - [ ] get total trackeado por day para la ultima semana
    - [ ] get media de trackeo por día 

## aceptación

- un usuario puede visualizar de forma directa que "planificación" tiene para un objetivo (semanalmente) y puede ver como de certero esta siendo
