### ISSUE TITLE
config - workflows y despliegue (CI/CD)

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#62]
## descripción

definir e implementar los workflows base de construcción, testeo y despliegue de la aplicación

## to-do

- [x] configurar la app en azure
- [x] obtener la información requerida para automatizar despliegues a azure
- [x] usar workflow de despliegue a azure (existen en el listado de github)
- [x] implementar workflows para:
    - [x] build / test backend
    - [x] build / test frontend
    - [x] codacy report
    - [x] desployment
