### ISSUE TITLE
doc - inicio, plan y diseño

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#64]
## descripcion
revisar la documentación de las fases iniciales del proyecto y pasarlas a la memoria, haciendo uso de la wiki y la memoria

## to-do
- [ ] comprobar usabilidad de formato markdown en latex
- [x] documentar el Inicio
- [ ] documentar la Planificación
- [ ] documentar el Diseño

## recursos
- memoria
- wiki
