### ISSUE TITLE
OP2 Story: Imagenes de post y usuario

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#65]
## descripción

_como_: usuario

_quiero_: poder subir una imagen adjunta a mi post o mi perfil

_para_: poder dar información visual

## to-do

- [x] añadir a formularios
    - [x] crear media en cuanto se seleccione en el formulario
    - [x] enviar el post y la id de la media generada
- [x] api
    - [x] endpoint para subir media 

## aceptación

- un usuario puede especificar una imagen en los formularios de perfil y post que quedará ligada a estos

**Comment by JSnow11** [comment]
## metodo
- frontend llama al endpoint de crear imagen y recibe un id o url
- backend sube la imagen, y guarda en bd la url y el id
- frontend enviará la id o url en los formularios de creación de las entidades relacionadas (media: "<id>")
