### ISSUE TITLE
Story: Permisos sobre los recursos de la aplicacion

### ISSUE THREAD

**Issue by pedalopon** [P2JN/doit#79]
## descripción

_como_: usuario 

_quiero_: que otros usuarios no puedan modificar, borrar o leer datos a los que solo yo debería tener acceso

_para_: asegurar mi privacidad y la integridad de mis datos.

## to-do

- [x] Implementar comprobaciones de permisos según el usuario logeado
- [x] Implementar lógicas complejas de seguridad relacionadas con el ámbito de la aplicación

## aceptación

- [x] No se pueden borrar o editar entidades que no pertenecen al usuario
- [ ] No se pueden leer entidades que no debería leer el usuario 
- [ ] Demás lógicas complejas de seguridad
