### ISSUE TITLE
General Story: Barra de búsqueda

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#86]
## descripción

_como_: usuario

_quiero_: poder buscar usuarios, posts y objetivos

_para_: poder encontrar lo que busco facilmente

## to-do

- [x] barra de búsqueda
- [x] API ya implementada en #61 

## aceptación

- [x] un usuario puede buscar objetivos, posts y usuarios
