### ISSUE TITLE
OP2 Story: mis seguidores 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#94]
## descripción

_como_: usuario

_quiero_: poder ver una lista de mis seguidores y otra de a quien sigo

_para_: poder visualizar seguidores y seguidos facilmente

## to-do
- [ ] lista de seguidores (modal)
    - [ ] en mi perfil / detalles de usuario
- [ ] lista de seguidos (modal)
    - [ ] en mi perfil / detalles de usuario   
- [x] API
    - [x] get followers ( devuelve users no ids )
    - [x] get following ( devuelve users no ids ) 

## aceptación

- se debe poder listar seguidos y seguidores
