### ISSUE TITLE
General Story: recomendaciones en explore 

### ISSUE THREAD

**Issue by JSnow11** [P2JN/doit#98]
## descripción

_como_: usuario

_quiero_: tener recomendaciones relevantes en la pagina de explore

_para_: poder acceder a contenido de mi interés

## to-do

- [ ] Slideshows para teasers de goal, usuario y post, por diferentes tipos de recomendación
- [ ] API
    - [ ] recomendar usuarios por
        - [x] followers (cantidad y crecimiento)
        - [x] actividad (posts y trackings medios)
        - [x] afinidad (semejanza al usuario o participación en goals semejantes)
        - [ ] puntuación (calculo en #47)  
    - [ ] recomendar goals por:
        - [x] participantes (cantidad y crecimiento)
        - [x] following (goals de las personas a las que sigues)
        - [x] afinidad (goals semejantes a los que participas)
        - [x] actividad (trackings) (cantidad y crecimiento) 
     - [ ] posts
        - [ ] relevancia (comentarios y likes de usuarios distintos)
        - [ ] following (goals de las personas a las que sigues)

## aceptación

- la pagina de explore ofrece recomendaciones relevantes

**Comment by JSnow11** [comment]
## adicional
- recientes (los ultimos 10)
